spring:
  application:
    name: onlinebooktrackerapp
  security:
    oauth2:
      client:
        registration:
          github:
             client-id:
             client-secret:

          google:
            client-id:
            client-secret:

  data:
    cassandra:
      keyspace-name:
      username:
      password:
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
    secure-connect-bundle: secure-connect-onlinebooktrackerapp.zip


astra.db:
    id:
    region: asia-south1
    keyspace:
    application.token:
